name: Anything Compiler

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Android
      run: |
        echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
    - name: Adopt
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 16
    - name: Assemble
      run: chmod 755 ./gradlew; ./gradlew deploy -Duse-k2
    - name: Anticipate
      uses: svenstaro/upload-release-action@2.3.0
      with:
        repo_name: PKChaos/Anything
        file: build/libs/Anything.jar
        tag: ${{ github.run_number }}
        body: |
          'No other thing.'
